datasource.db.username=benchmarkdbuser
datasource.db.password=benchmarkdbpass
datasource.db.url=jdbc:postgresql://${host:tfb-database}:5432/hello_world?user=${datasource.db.username}&password=${datasource.db.password}